name: Job Artifacts
on: workflow_dispatch
jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - name: Create first file to upload
        run: echo "hello" > output1.txt
      - name: Create second file to upload
        run: echo "world" > output2.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            output1.txt
            output2.txt
  job_b:
    runs-on: ubuntu-latest
    # Required here so that upload can happen first.
    needs: job_a
    steps:
      - name: Download artifact  
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      # After downloading, the folder contents are 
      # automatically moved to the unzipped folder,
      # and the terminal is automatically 
      # navigated to that location.
      - name: List the downloaded files
        run: ls

