name: Job Artifacts
on: workflow_dispatch
jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - name: Create first file to upload
        run: echo "hello" > output1.txt
      - name: Create second file to upload
        run: echo "world" > output2.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            output1.txt
            output2.txt


