name: Across Steps Example
on: workflow_dispatch

jobs:
  across-steps-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate data
        id: source_step
        run: |
          # Store the output using GITHUB_OUTPUT
          echo "key1=Hello" >> "$GITHUB_OUTPUT"
          echo "key2=World" >> "$GITHUB_OUTPUT"
          echo "Location of GITHUB_OUTPUT FILE $GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT

      - name: Consume data
        run: |
          echo "Location of GITHUB_OUTPUT FILE $GITHUB_OUTPUT"
          # Reference the output using the context: steps.<step_id>.outputs.<key>
          echo "Key1 value is ${{ steps.source_step.outputs.key1 }}"
          echo "Key2 value is ${{ steps.source_step.outputs.key2 }}"
